//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roabotn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLogin
    {
        public int IdAdmin { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string surname { get; set; }
        public int IdStatus { get; set; }
        public Nullable<int> IdDepartment { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Status Status { get; set; }
    }
}
