//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roabotn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskWorker
    {
        public int IdTaskWorker { get; set; }
        public Nullable<int> IdTasks { get; set; }
        public Nullable<int> IdWorker { get; set; }
    
        public virtual Tasks Tasks { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
