//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roabotn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.TaskWorker = new HashSet<TaskWorker>();
        }
    
        public int IdWorker { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string surname { get; set; }
        public string number { get; set; }
        public string email { get; set; }
        public string INN { get; set; }
        public string Snils { get; set; }
        public string Adress { get; set; }
        public string PasportSeries { get; set; }
        public string PasportNumber { get; set; }
        public int IdDepartment { get; set; }
        public Nullable<int> IdTasks { get; set; }
        public string Specialnost { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskWorker> TaskWorker { get; set; }
    }
}
